### ISSUE TITLE
gild-checkout fail on linux

### ISSUE THREAD

**Issue by afxgroup** [sba1/gild#1]
gild-checkout on linux fail in line

call(["git", "checkout", checkout, "-B", branch])

because -B should be -b

**Comment by sba1** [comment]
Which version of git are you using? The -B is supported for the required purpose.
See ```man git checkout```:
```git checkout [-q] [-f] [-m] [[-b|-B|--orphan] <new_branch>] [<start_point>]```

**Comment by afxgroup** [comment]
git version 1.7.1 on Centos 6
It is the version installed with "yum install git"

**Comment by sba1** [comment]
I suggest to use a newer version of git that supports this -B. I don't know if it is worth to maintain compatibility with very old git versions. For Centos, I saw e.g. this: https://stackoverflow.com/questions/21820715/how-to-install-latest-version-of-git-on-centos-6-x-7-x

However, feel free to issue a pull request that uses -b when -B is not supported.

**Comment by sba1** [comment]
Closing this now.
