### ISSUE TITLE
Python path is hardcoded everywhere

### ISSUE THREAD

**Issue by Midar** [sba1/gild#3]
The Python part in all files using a shebang is hardcoded to be /usr/bin/python. It would be better to use #!/usr/bin/env python3 instead, to make sure the correct python version is used.

Making this even worse, gild is calling other Python scripts via the shell, so that even when running python3 ./gild list, it will call into the wrong Python again. These calls should be changed to use the currently running Python interpreter instead.

**Comment by sba1** [comment]
> Making this even worse, gild is calling other Python scripts via the shell, so that even when running python3 ./gild list, it will call into the wrong Python again. These calls should be changed to use the currently running Python interpreter instead.

Technically, there is no need for these files being python scripts so I don't think that should be changed. The commands are more or less independent from the main driver.

I added the env stuff. I have not tested the scripts with Python 3, so it will require 2.7 until it is clear that it works.

**Comment by Midar** [comment]
I patched all the files manually to use my python 3 and it worked fine, I'm guessing it's safe :). I built adtools with it successfully.

**Comment by 3246251196** [comment]
Please see and consider: https://github.com/sba1/gild/pull/8.

**Comment by sba1** [comment]
Done.
