### ISSUE TITLE
GILD no longer allows COMMIT IDs in "series"

### ISSUE THREAD

**Issue by 3246251196** [sba1/gild#9]
To reproduce
- clone ADTOOLS proper
- cd into it, and,
- git submodule init
- git submodule update
- gild/bin/gild checkout gcc 4.9

Notice error:
```
Cloning into 'repo'...
warning: Could not find remote branch 876d41ed80ce13e060084ed5a552c37c301e5563 to clone.
fatal: Remote branch 876d41ed80ce13e060084ed5a552c37c301e5563 not found in upstream origin
Traceback (most recent call last):
  File "/home/rjd/projects/adtools_rjd/gild/bin/gild-checkout", line 70, in <module>
    os.chdir(repo_path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/rjd/projects/adtools_rjd/gcc/repo'
```

The exact command attempted was:
```
git clone  https://github.com/gcc-mirror/gcc  --depth=1 -b 876d41ed80ce13e060084ed5a552c37c301e5563 repo
```

===

This issue also - therefore - affects the **ReadMe.md** file.

**Comment by sba1** [comment]
This actually would be a bug in the adtools repo as the description which SHA1 to use is there. Maybe the gcc team has changed the history. Please report the bug in this repo.

**Comment by 3246251196** [comment]
I am still not sure this works - despite there being a now non-existent commit ID (which was handled by you this morning).

But, consider the following:

The general command that gild will use is the one in my original post.

You can try the following steps:
- clone gcc (//github.com/gcc-mirror/gcc)
- git log cd37325b8d500bf4021692620686572d5ffb0868
- See that it exists
- cd to somewhere random
- git clone  https://github.com/gcc-mirror/gcc  -b cd37325b8d500bf4021692620686572d5ffb0868 repo
- Notice: 
```
warning: Could not find remote branch cd37325b8d500bf4021692620686572d5ffb0868 to clone.
fatal: Remote branch cd37325b8d500bf4021692620686572d5ffb0868 not found in upstream origin
```

It does not seem possible to use specific IDs.

**Comment by sba1** [comment]
Ok I see. The adtools repo has been fixed to use branches or tags. I can't remember exactly whether the SHA1 used to work in the past but I think so. Perhaps, something in the git interface has been changed? That said, I think that the problem is fixed in the adtools repo. If also plain SHA1 ids are needed, gild needs to learn it again. This would be considered as a new feature.

**Comment by 3246251196** [comment]
Right, I agree that the bad commit ID with 4.9 is now fixed by using a named reference. Good.

I also suspect that something in the interface has probably changed.

If you re-open this issue I can look into it and create a PR in the near future.
